version: "3.9"

services:
  postgres:
    image: anirudhc2402/startupforge-postgres:base
    container_name: startupforge-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: startupforge_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  neo4j:
    image: anirudhc2402/startupforge-neo4j:base
    container_name: startupforge-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j_volume1:/data
      - neo4j_volume2:/logs

volumes:
  pgdata:
  neo4j_volume1:
  neo4j_volume2:
